DIALECT=$1
SECOND_ARG=$2

# Check that dialect is correct
if [ "$DIALECT" != "mysql" ] && [ "$DIALECT" != "postgresql" ] && [ "$DIALECT" != "clickhouse" ]
then
  echo "dialect '$DIALECT' is not supported"
  exit 0
fi

# Select the correct file prefix
if [ "$DIALECT" == "mysql" ]
then
  FILE_PREFIX=src/parsers/$DIALECT/generated/MySql
elif [ "$DIALECT" == "postgresql" ]
then
  FILE_PREFIX=src/parsers/$DIALECT/generated/PostgreSql
else
  FILE_PREFIX=src/parsers/$DIALECT/generated/ClickHouse
fi

HEADER="////////////////////////////////////////////////////////
// THIS FILE IS AUTOGENERATED, DON'T EDIT IT MANUALLY //
////////////////////////////////////////////////////////\n\n// We don't really want to check types in generated code\n// @ts-nocheck\n\n"

declare -a FILES_TO_PATCH=(
  ${FILE_PREFIX}Lexer.ts
  ${FILE_PREFIX}Parser.ts
  ${FILE_PREFIX}ParserVisitor.ts
)

echo "Patching ${DIALECT} generated files"

for FILE in "${FILES_TO_PATCH[@]}"
do
  # Add header
  ECHO_TEXT=$HEADER

  # Add extra postgresql patches if asked
  if ! [ -z "$SECOND_ARG" ] && [ $SECOND_ARG = "--extra-postgresql-patches" ]
  then
    if [[ $FILE == *Parser.ts* ]]
    then
      # Add missing base class import
      ECHO_TEXT="${ECHO_TEXT}import PostgreSqlParserBase from '../grammar/PostgreSqlParserBase.js';"

      # Fix missing package reference
      # -i '' is provided instead of just -i, because on mac -i treats -e as the backup file extension https://stackoverflow.com/questions/4247068/sed-command-with-i-option-failing-on-mac-but-works-on-linux
      # This bug is weird, we might fix it later if it's gonna be a pain
      sed -i '' -e 's/ ParserRuleContext/ antlr.ParserRuleContext/g' $FILE
    fi

    if [[ $FILE == *Lexer.ts* ]]
    then
      # Add missing base class import
      ECHO_TEXT="${ECHO_TEXT}import PostgreSqlLexerBase from '../grammar/PostgreSqlLexerBase.js';"
    fi
  fi

  # Add file contents
  ECHO_TEXT="$ECHO_TEXT\n\n$(cat $FILE)"

  echo -e "$ECHO_TEXT" > $FILE
  echo -e "- patched $FILE"
done

echo -e "Successfully patched everything\n"