FILE_PREFIX=src/parsers/postgresql/generated

LEXER_FILE=$FILE_PREFIX/PostgreSqlLexer.ts
PARSER_FILE=$FILE_PREFIX/PostgreSqlParser.ts
PARSER_VISITOR_FILE=$FILE_PREFIX/PostgreSqlParserVisitor.ts

HEADER="////////////////////////////////////////////////////////
// THIS FILE IS AUTOGENERATED, DON'T EDIT IT MANUALLY //
////////////////////////////////////////////////////////\n\n// We don't really want to check types in generated code\n// @ts-nocheck\n\n"

declare -a FILES_TO_PATCH=(
  $LEXER_FILE
  $PARSER_FILE
  $PARSER_VISITOR_FILE
)

for FILE in "${FILES_TO_PATCH[@]}"
do
  # Add header
  ECHO_TEXT=$HEADER

  # Add optional stuff
  if [ $1 = "--add-postgresql-imports" ]
  then
    ECHO_TEXT="$ECHO_TEXT\nimport PostgreSqlParserBase from '../grammar/PostgreSqlParserBase.js';"
    ECHO_TEXT="$ECHO_TEXT\nimport PostgreSqlLexerBase from '../grammar/PostgreSqlLexerBase.js';"
  fi

  # Add file contents
  ECHO_TEXT="$ECHO_TEXT\n\n$(cat $FILE)"

  echo -e "$ECHO_TEXT" > $FILE
done

echo 'successfully patched generated postgresql files'